services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: fastapi-app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    container_name: frontend-app
    depends_on:
      - backend 