services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend
networks:
  app-network:
    driver: bridge
